# Install
if(!require(devtools)) install.packages("devtools")
devtools::install_github("kassambara/ggcorrplot")

library(ggcorrplot)

#read colocalization file generated by multiBigwigSummary and save as .csv
Colocalization <- read.table(file='./Data/200224Corrplot.txt',row.names=1,header=T)
head (Colocalization)

#plot correlation heatmap using ggplot
ggColocalization <- ggcorrplot(Colocalization,sig.level=0.05,hc.order=T,lab_col = "black",lab_size = 12,p.mat=NULL,tl.cex = 9, tl.col = "black", tl.srt = 90, digits = 2) +
theme(axis.text.x = element_text(margin=margin(-2,0,0,0)),
                                                                        axis.text.y = element_text(margin=margin(0,-2,0,0)),
                                                                        panel.grid.minor = element_line(size=10)) + 
  geom_tile(height=0.8, width=0.8) +
  scale_fill_gradient2(limit = c(0,1), low = "white", high =  "red1", mid = "white", midpoint = 0.33)

ggsave('./Figures/ColocalizationPlot2.png',plot=ggColocalization,dpi=800)

